name: Build wasm package
run-name: Build package
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cargo install \ 
        wasm-pack build --target nodejs