name: Test Trade Engine
run-name: Run cargo tests
on: [push]
jobs:
  cargo_test:
    runs-on: ubuntu-latest
    name: Test with cargo
    steps:
      - run: |
        cargo install \
        cargo test